### ISSUE TITLE
Why it will effect left? Is it a bug?  how to keey the left immobility

### ISSUE THREAD

**Issue by xqdd** [toufikzitouni/flutter-bidirectional_scrollview_plugin#11] opened 2019-04-20 16:12 UTC
![2019-04-21_00-11-30](https://user-images.githubusercontent.com/20871761/56459705-12b66e00-63ca-11e9-8953-61c705473ff0.gif)

```dart
import 'package:bidirectional_scroll_view/bidirectional_scroll_view.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  BidirectionalScrollViewPlugin _plugin;

  @override
  void initState() {
    super.initState();
    _plugin = new BidirectionalScrollViewPlugin(
      child: _buildWidgets(),
      velocityFactor: 2.0,
    );

    //_plugin.offset = new Offset(10.0, 10.0); // use this method to set a new offset where appropriate
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Bidirectional ScrollView Plugin'),
        ),
        body: new Center(
            child: Row(
          children: [
            Expanded(
              flex: 1,
              child: Container(
                color: Colors.red,
                width: 100,
                height: 100,
              ),
            ),
            Expanded(
              flex: 1,
              child: _plugin,
            )
          ],
        )),
      ),
    );
  }

  Widget _buildWidgets() {
    List<Widget> list = new List();

    for (int i = 0; i < 1024; i++) {
      list.add(new Container(
        padding: new EdgeInsets.all(5.0),
        color: Colors.white,
        height: 80.0,
        width: 120.0,
        child: new Container(
          color: Colors.grey,
          child: Text("$i"),
        ),
      ));
    }

    return new Row(
      children: [
        new Column(
          children: list.map((widget) {
            return widget;
          }).toList(),
        ),
      ],
    );
  }
}


```

**Comment by The-Redhat** [comment] 2019-05-22 13:48
The problem is how the plugin handles overflows. I made a [pr](https://github.com/toufikzitouni/flutter-bidirectional_scrollview_plugin/pull/12). You can fix this issue by setting `scrollOverflow` to `Overflow.clip`.

**Comment by toufikzitouni** [comment] 2019-05-30 15:03
Merged the PR. Closing this but feel free to reopen if it occurs again

**Closed as completed by toufikzitouni** 2019-05-30 15:03 UTC
